name: Build and Deploy Docs

on:
  push:
    branches:
      - main
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout 🛎️
      uses: actions/checkout@master
      
    - name: Use Node.js 12
      uses: actions/setup-node@v2-beta
      with:
        node-version: '12'

    - name: Install and Build 🔧 
      run: |
        cd docs
        npm install
        npm run docs:build

    - name: Deploy 🚀
      uses: JamesIves/github-pages-deploy-action@3.7.1
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        BRANCH: gh-pages
        FOLDER: docs/docs/.vuepress/dist

    - name: Upyun Refresh
      uses: yiyungent/upyun-action@main
      with:
        # 在 Settings->Secrets 配置 UPYUN_USERNAME, UPYUN_PASSWORD
        upyun_username: ${{ secrets.UPYUN_USERNAME }}
        upyun_password: ${{ secrets.UPYUN_PASSWORD }}
        # 要刷新的url, 支持匹配符 *, 多个url中间用 \n 隔开
        refresh_cache_urls: "https://moeci.com/PluginCore/*\nhttps://moeci.com/PluginCore"
        upyun_debug: true