name: Sync to Gitea

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Sync to Gitea
        uses: wearerequired/git-mirror-action@master
        env:
          # 在 Settings->Secrets 配置 GITEA_SSH_PRIVATE_KEY
          SSH_PRIVATE_KEY: ${{ secrets.GITEA_SSH_PRIVATE_KEY }}
        with:
          # 源仓库地址
          source-repo: git@github.com:yiyungent/PluginCore.git
          # 目标仓库地址
          destination-repo: ssh://git@gitea.moeci.com:222/yiyungent/PluginCore.git
